### ISSUE TITLE
[Feature] Override extension lists

### ISSUE THREAD

**Issue by cobaltgit** [ryusatgat/trimuitool#1]
Some config.json files for certain emulators (i.e. PSP, Sega Saturn) don't have an "extlist" attribute, meaning the extlist defaults to just `zip`. Would it be possible to implement it so that you can input the extension list into the box (pipe separated) and have it rescan?

**Comment by ryusatgat** [comment]
Seems like a good idea. We will be adding that feature soon.

**Comment by ryusatgat** [comment]
v0.94 Scan ROM extension button added. 'db', 'xml', 'txt', 'state' extensions will not append.
This action does not refresh the ROM list, so click the "Generate cache" button to add a new ROMs.

**Comment by ryusatgat** [comment]
Function added.
